sudo: required
addons:
  apt:
    packages:
    - qemu
    - qemu-user-static
    - binfmt-support
    - parted
    - wget
    - dosfstools
    - zip
script:
- sudo bash ./create-image
- xz -z dlbian.img -c > dlbian.img.xz
- zip dlbian.img.zip dlbian.img
